<a href="https://colab.research.google.com/github/Prathambiradr12345/Natural-Langauge-Proccessing/blob/main/Text_representation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Text-vectorization or text representation or feature extraction=convert text to number

In [ ]:
#techniques=OHE(One Hot Encoding)
#corpus (c)=in dataset sare words jodne ke technique ko
#Vocabulary (v)=unique words in dataset
#Document (D)=every review called documennt
#word (w)=
#disadvantage=sparsity,No fixed Size,out of vocabulary
#not used Ohe

In [ ]:
#techniques=bag of words
#used for text classfication

In [1]:
import numpy as np
import pandas as pd
df=pd.DataFrame({'text':['people watch campusx','campusx watch campusx','people write comment','campusx write comment'],'output':[1,1,0,0]})

In [2]:
df

text  output
0   people watch campusx       1
1  campusx watch campusx       1
2   people write comment       0
3  campusx write comment       0

In [3]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer()
bow=cv.fit_transform(df['text'])

In [4]:
#vocabulary
print(cv.vocabulary_)


{'people': 2, 'watch': 3, 'campusx': 0, 'write': 4, 'comment': 1}


In [5]:
print(bow[0].toarray())
print(bow[1].toarray())

[[1 0 1 1 0]]
[[2 0 0 1 0]]


In [7]:
cv.transform(['campusx watch and write comment of  ']).toarray()

array([[1, 1, 0, 1, 1]])

In [ ]:
#disadvantages of bag of words
#ordering issue in words,changes in statement not capture

In [8]:
#techniques=Bag of n-grams
#Bi-grams,uni-grams,tri-grams
df

text  output
0   people watch campusx       1
1  campusx watch campusx       1
2   people write comment       0
3  campusx write comment       0

In [14]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(ngram_range=(1,3))
bow=cv.fit_transform(df['text'])

In [17]:
#vocab
print(len(cv.vocabulary_))
print(cv.vocabulary_)

15
{'people': 6, 'watch': 11, 'campusx': 0, 'people watch': 7, 'watch campusx': 12, 'people watch campusx': 8, 'campusx watch': 1, 'campusx watch campusx': 2, 'write': 13, 'comment': 5, 'people write': 9, 'write comment': 14, 'people write comment': 10, 'campusx write': 3, 'campusx write comment': 4}


In [16]:
print(bow[0].toarray())
print(bow[1].toarray())

[[1 0 0 0 0 0 1 1 1 0 0 1 1 0 0]]
[[2 1 1 0 0 0 0 0 0 0 0 1 1 0 0]]


In [ ]:
#advantages & disadvantages
#dimesionality increases,time complexcity increases

In [18]:
#techniques=Tf-Idf(term frequency-inverse doc.frequency)
#tf-particular term kitna important hai document
#idf=corpus ke liye kitna important hai
df

text  output
0   people watch campusx       1
1  campusx watch campusx       1
2   people write comment       0
3  campusx write comment       0

In [19]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer()
tfidf.fit_transform(df['text']).toarray()

array([[0.49681612, 0.        , 0.61366674, 0.61366674, 0.        ],
       [0.8508161 , 0.        , 0.        , 0.52546357, 0.        ],
       [0.        , 0.57735027, 0.57735027, 0.        , 0.57735027],
       [0.49681612, 0.61366674, 0.        , 0.        , 0.61366674]])

In [20]:
print(tfidf.idf_)
print(tfidf.get_feature_names_out())

[1.22314355 1.51082562 1.51082562 1.51082562 1.51082562]
['campusx' 'comment' 'people' 'watch' 'write']


In [ ]:
#why use in idf calculating log?
#eg.idf=10000 movie reviews then df is very less idf is very high


In [ ]:
#advantages & disadvantages
#advantages=it used for seo
#disadvantages=sparse city,out of vocabulary

In [ ]:
#techniques=custom features
#2types=techniques,custom
#types of features called hybrid features